package com.markkryzh.entity;
// Generated 19 ����. 2017 0:27:24 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Community generated by hbm2java
 */
@Entity
@Table(name = "community", schema = "public")
public class Community implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;
	private Set<Membership> memberships = new HashSet<Membership>(0);
	private Set<PollCommunity> pollCommunities = new HashSet<PollCommunity>(0);
	private String membersNamesStr;
	private List<User> members;
	private Date created;
	public Community() {
	}

	public Community(User user, String name) {
		super();
		this.user = user;
		this.name = name;
	}
	
	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
	
	@Column(name = "name")
	@NotEmpty(message = "*Please provide community name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "community")
	public Set<Membership> getMemberships() {
		return this.memberships;
	}

	public void setMemberships(Set<Membership> memberships) {
		this.memberships = memberships;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "community")
	public Set<PollCommunity> getPollCommunities() {
		return this.pollCommunities;
	}

	public void setPollCommunities(Set<PollCommunity> pollCommunities) {
		this.pollCommunities = pollCommunities;
	}
	@Transient
	public String getMembersNamesStr() {
		return membersNamesStr;
	}

	public void setMembersNamesStr(String membersNamesStr) {
		this.membersNamesStr = membersNamesStr;
	}

	@Transient
	public List<User> getMembers() {
		return members;
	}

	public void setMembers(List<User> members) {
		this.members = members;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", insertable = false, length = 29)
	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}
	
}
