package com.markkryzh.entity;
// Generated 19 ����. 2017 0:27:24 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PollTheme generated by hbm2java
 */
@Entity
@Table(name = "poll_theme", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class PollTheme implements java.io.Serializable {

	private Integer id;
	private User user;
	private String name;
	private String description;
	private Set<Poll> polls = new HashSet<Poll>(0);

	public PollTheme() {
	}

	public PollTheme(User user, String name, String description) {
		super();
		this.user = user;
		this.name = name;
		this.description = description;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pollTheme")
	public Set<Poll> getPolls() {
		return this.polls;
	}

	public void setPolls(Set<Poll> polls) {
		this.polls = polls;
	}
}
