package com.markkryzh.entity;
// Generated 5 ����. 2017 1:22:02 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.data.annotation.CreatedDate;

/**
 * PollResult generated by hbm2java
 */
@Entity
@Table(name = "poll_result", schema = "public")
public class PollResult implements java.io.Serializable {

	private Integer id;
	private PollAnswer pollAnswer;
	private User user;
	private Date date;

	public PollResult() {
	}
	

	public PollResult(PollAnswer pollAnswer, User user) {
		super();
		this.pollAnswer = pollAnswer;
		this.user = user;
	}


	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_answer_id", nullable = false)
	public PollAnswer getPollAnswer() {
		return this.pollAnswer;
	}

	public void setPollAnswer(PollAnswer pollAnswer) {
		this.pollAnswer = pollAnswer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", insertable = false,length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
