package com.markkryzh.entity;
// Generated 5 ����. 2017 18:39:50 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.markkryzh.entity.User.UserPermissions;

/**
 * Poll generated by hbm2java
 */
@Entity
@Table(name = "poll", schema = "public")
public class Poll implements java.io.Serializable {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Poll other = (Poll) obj;
		if (id == null) {
			return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	private Integer id;
	private long usersVoted;
	private PollTheme pollTheme;
	private User user;
	private String name;
	private boolean privat;
	private boolean anonymous;
	private boolean showAuthor;
	private Date date;
	private Date fromTimestamp;
	private Date toTimestamp;
	private String hashTags;
	private Set<Test> tests = new HashSet<>();
	private Set<PollQuestion> pollQuestions = new HashSet<PollQuestion>(0);
	private Set<PollCommunity> pollCommunities = new HashSet<PollCommunity>(0);

	public Poll() {
	}

	public Poll(PollTheme pollTheme, User user, String name, boolean privat, boolean anonymous, boolean showAuthor,
			String image, Date fromTimestamp, Date toTimestamp, String hashTags, Set<PollQuestion> pollQuestions) {
		super();
		setDate(null);
		this.pollTheme = pollTheme;
		this.user = user;
		this.name = name;
		this.privat = privat;
		this.anonymous = anonymous;
		this.showAuthor = showAuthor;
		this.fromTimestamp = fromTimestamp;
		this.toTimestamp = toTimestamp;
		this.hashTags = hashTags;
		this.pollQuestions = pollQuestions;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "poll_theme_id")
	public PollTheme getPollTheme() {
		return this.pollTheme;
	}

	public void setPollTheme(PollTheme pollTheme) {
		this.pollTheme = pollTheme;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "anonymous", nullable = false)
	public boolean isAnonymous() {
		return this.anonymous;
	}
	
	@Column(name = "private", nullable = false)
	public boolean isPrivat() {
		return privat;
	}

	public void setPrivat(boolean privat) {
		this.privat = privat;
	}

	public void setAnonymous(boolean anonymous) {
		this.anonymous = anonymous;
	}

	@Column(name = "show_author", nullable = false)
	public boolean isShowAuthor() {
		return this.showAuthor;
	}

	public void setShowAuthor(boolean showAuthor) {
		this.showAuthor = showAuthor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", insertable = false, length = 29)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from_timestamp", length = 29)
	public Date getFromTimestamp() {
		return this.fromTimestamp;
	}

	public void setFromTimestamp(Date fromTimestamp) {
		this.fromTimestamp = fromTimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "to_timestamp", length = 29)
	public Date getToTimestamp() {
		return this.toTimestamp;
	}

	public void setToTimestamp(Date toTimestamp) {
		this.toTimestamp = toTimestamp;
	}

	@Column(name = "hash_tags")
	public String getHashTags() {
		return this.hashTags;
	}

	public void setHashTags(String hashTags) {
		this.hashTags = hashTags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poll")
	public Set<Test> getTests() {
		return this.tests;
	}

	public void setTests(Set<Test> tests) {
		this.tests = tests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poll")
	public Set<PollQuestion> getPollQuestions() {
		return this.pollQuestions;
	}

	public void setPollQuestions(Set<PollQuestion> pollQuestions) {
		this.pollQuestions = pollQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poll")
	public Set<PollCommunity> getPollCommunities() {
		return this.pollCommunities;
	}

	public void setPollCommunities(Set<PollCommunity> pollCommunities) {
		this.pollCommunities = pollCommunities;
	}

	@Transient
	public long getUsersVoted() {
		return usersVoted;
	}

	public void setUsersVoted(long usersVoted) {
		this.usersVoted = usersVoted;
	}

}
