package com.markkryzh.entity;
// Generated 5 ����. 2017 1:22:02 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.markkryzh.entity.Poll;
import com.markkryzh.entity.PollAnswer;
import com.markkryzh.entity.Test;

/**
 * PollQuestion generated by hbm2java
 */
@Entity
@Table(name = "poll_question", schema = "public")
public class PollQuestion implements java.io.Serializable {

	private Integer id;
	private Poll poll;
	private String text;
	private boolean allowOtherAnswer;
	private String image;
	private Set<PollAnswer> pollAnswers = new HashSet<PollAnswer>(0);

	public PollQuestion() {
	}
	
	public PollQuestion(Poll poll, String text, boolean allowOtherAnswer, String image, Set<PollAnswer> pollAnswers) {
		super();
		this.poll = poll;
		this.text = text;
		this.allowOtherAnswer = allowOtherAnswer;
		this.image = image;
		this.pollAnswers = pollAnswers;
	}

	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_id", nullable = false)
	public Poll getPoll() {
		return this.poll;
	}

	public void setPoll(Poll poll) {
		this.poll = poll;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "allow_other_answer", nullable = false)
	public boolean isAllowOtherAnswer() {
		return this.allowOtherAnswer;
	}

	public void setAllowOtherAnswer(boolean allowOtherAnswer) {
		this.allowOtherAnswer = allowOtherAnswer;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pollQuestion")
	public Set<PollAnswer> getPollAnswers() {
		return this.pollAnswers;
	}

	public void setPollAnswers(Set<PollAnswer> pollAnswers) {
		this.pollAnswers = pollAnswers;
	}
}
