package com.markkryzh.entity;
// Generated 5 ����. 2017 1:22:02 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.markkryzh.entity.PollQuestion;

/**
 * PollAnswer generated by hbm2java
 */
@Entity
@Table(name = "poll_answer", schema = "public")
public class PollAnswer implements java.io.Serializable {

	private Integer id;
	private PollQuestion pollQuestion;
	private String text;
	private boolean other;
	private String image;
	private Set<PollResult> pollResults = new HashSet<PollResult>(0);

	public PollAnswer() {
	}

	public PollAnswer(PollQuestion pollQuestion, String text, boolean other, String image) {
		super();
		this.pollQuestion = pollQuestion;
		this.text = text;
		this.other = other;
		this.image = image;
	}
	
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poll_question_id", nullable = false)
	public PollQuestion getPollQuestion() {
		return this.pollQuestion;
	}

	public void setPollQuestion(PollQuestion pollQuestion) {
		this.pollQuestion = pollQuestion;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "other", nullable = false)
	public boolean isOther() {
		return this.other;
	}

	public void setOther(boolean other) {
		this.other = other;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pollAnswer")
	public Set<PollResult> getPollResults() {
		return this.pollResults;
	}

	public void setPollResults(Set<PollResult> pollResults) {
		this.pollResults = pollResults;
	}
}
