package com.markkryzh.entity;
// Generated 19 ����. 2017 0:27:24 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestAnswerScore generated by hbm2java
 */
@Entity
@Table(name = "test_answer_score", schema = "public")
public class TestAnswerScore implements java.io.Serializable {

	private Integer id;
	private Category category;
	private TestAnswer testAnswer;
	private int score;

	public TestAnswerScore() {
	}
	
	public TestAnswerScore(Category category, TestAnswer testAnswer, int score) {
		super();
		this.category = category;
		this.testAnswer = testAnswer;
		this.score = score;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_answer_id", nullable = false)
	public TestAnswer getTestAnswer() {
		return this.testAnswer;
	}

	public void setTestAnswer(TestAnswer testAnswer) {
		this.testAnswer = testAnswer;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

}
