package com.markkryzh.entity;
// Generated 19 ����. 2017 0:27:24 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestQuestion generated by hbm2java
 */
@Entity
@Table(name = "test_question", schema = "public")
public class TestQuestion implements java.io.Serializable {

	private Integer id;
	private Test test;
	private String text;
	private String image;
	private Set<TestAnswer> testAnswers = new HashSet<>();

	public TestQuestion() {
	}

	public TestQuestion(Test test, String text, String image, Set<TestAnswer> testAnswers) {
		super();
		this.test = test;
		this.text = text;
		this.image = image;
		this.testAnswers = testAnswers;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_id")
	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testQuestion")
	public Set<TestAnswer> getTestAnswers() {
		return this.testAnswers;
	}

	public void setTestAnswers(Set<TestAnswer> testAnswers) {
		this.testAnswers = testAnswers;
	}
}
