package com.markkryzh.entity;
// Generated 19 ����. 2017 0:27:24 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestAnswer generated by hbm2java
 */
@Entity
@Table(name = "test_answer", schema = "public")
public class TestAnswer implements java.io.Serializable {

	private Integer id;
	private TestQuestion testQuestion;
	private String text;
	private String image;
	private Set<TestAnswerScore> testAnswerScores = new HashSet<>();

	public TestAnswer() {
	}
	
	public TestAnswer(TestQuestion testQuestion, String text, String image, Set<TestAnswerScore> testAnswerScores) {
		super();
		this.testQuestion = testQuestion;
		this.text = text;
		this.image = image;
		this.testAnswerScores = testAnswerScores;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "test_question_id", nullable = false)
	public TestQuestion getTestQuestion() {
		return this.testQuestion;
	}

	public void setTestQuestion(TestQuestion testQuestion) {
		this.testQuestion = testQuestion;
	}

	@Column(name = "text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "image")
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testAnswer")
	public Set<TestAnswerScore> getTestAnswerScores() {
		return this.testAnswerScores;
	}

	public void setTestAnswerScores(Set<TestAnswerScore> testAnswerScores) {
		this.testAnswerScores = testAnswerScores;
	}
}
